time_zone: 9
toggl:
  token: # Required
  time_entry:
    workspace_id:
    project_id:
    task_id:
    billable: False # Not required
    tags:
      - 睡眠
garmin:
  email: # Required
  password: # Required